In [1]:
import pandas as pd

In [2]:
popu = pd.read_csv("data/population.csv")

In [6]:
popu.loc[:,"race"]

0          chinese
1          chinese
2          chinese
3          chinese
4          chinese
            ...
2705110      malay
2705111     indian
2705112     indian
2705113     indian
2705114      other
Name: race, Length: 2705115, dtype: object

In [3]:
popu

         year_of_birth     race  gender
0                 1990  chinese    male
1                 1990  chinese    male
2                 1990  chinese    male
3                 1990  chinese    male
4                 1990  chinese    male
...                ...      ...     ...
2705110           1890    malay  female
2705111           1890   indian    male
2705112           1890   indian    male
2705113           1890   indian  female
2705114           1890    other  female

[2705115 rows x 3 columns]

In [28]:
popu2 = pd.read_csv("data/M810801.csv", index_col=0, header=0, engine='python' )

In [44]:
popu2.iloc[175:261,]

,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
Data Series,,,,,,,,,,,,,,,,,,,,,
0 Year,3705,3996,4246,3976,4113,3884,3999,3790,3672,3423,...,4431,4445,4552,4666,4736,5070,5040,4947,5194,5056
1 Year,4033,4299,4042,4197,3960,4102,3873,3760,3509,3441,...,4453,4570,4672,4752,5079,5051,4942,5203,5056,4921
2 Year,4303,4053,4228,3943,4106,3885,3763,3517,3453,3226,...,4582,4676,4756,5089,5060,4941,5209,5054,4913,4671
3 Year,4055,4240,3970,4101,3890,3778,3523,3469,3248,3099,...,4678,4763,5096,5069,4942,5218,5052,4904,4658,4198
4 Year,4246,3980,4124,3874,3779,3533,3466,3254,3110,3087,...,4767,5104,5076,4941,5225,5052,4899,4654,4190,4326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81 Year,434,380,475,503,522,471,423,418,536,448,...,259,226,148,131,112,195,223,130,147,118
82 Year,343,441,468,477,432,388,393,488,410,363,...,196,129,113,95,174,198,119,129,105,139
83 Year,399,425,434,392,360,351,439,375,334,285,...,113,99,87,154,179,104,117,87,123,86
84 Year,378,381,346,317,320,390,344,290,256,235,...,87,78,133,155,88,101,73,111,74,56
85 Years & Over,1733,1637,1605,1601,1579,1456,1366,1323,1316,1303,...,465,487,456,379,364,343,341,298,265,254

In [ ]:
pairs = [ (1,87), (88,174),(175,262),]

In [54]:
import numpy as np
import pandas as pd

# Define the dimensions of the matrix
result_matrix = np.zeros((8, 86, 35))

# Simulating popu2 for demonstration (you can replace this with your actual data)

# Initialize and fill the result_matrix
start = 1
for n in range(8):
    end = start + 86
    result_matrix[n, :, :] = popu2.iloc[start:end, :].to_numpy()[:, ::-1]  # Reversing columns 0 to 34
    start = end +1

# Save the result_matrix to a file (in binary format)

In [55]:
np.save('result_matrix.npy', result_matrix)

In [56]:
result_matrix_load = np.load('result_matrix.npy')

In [61]:
result_matrix.tofile('result_matrix_data.bin')

In [62]:
death_data = pd.read_csv("data/death_sg.csv", index_col=0, header=0, engine='python')

In [74]:
current_col

'1991'

In [75]:
death_data[next_col]

Data Series
Male Age Specific Death Rate        5.1
  Under 1 Year                      7.1
  1 - 4 Years                       0.4
  5 - 9 Years                       0.2
  10 - 14 Years                     0.3
  15 - 19 Years                     0.5
  20 - 24 Years                     0.8
  25 - 29 Years                     0.8
  30 - 34 Years                     0.9
  35 - 39 Years                     1.4
  40 - 44 Years                     2.1
  45 - 49 Years                     4.0
  50 - 54 Years                     6.8
  55 - 59 Years                    12.0
  60 - 64 Years                    20.8
  65 - 69 Years                    30.1
  70 - 74 Years                    46.9
  75 - 79 Years                    67.3
  80 - 84 Years                    97.2
  85 Years & Over                 142.3
Female Age Specific Death Rate      4.3
  Under 1 Year                      6.2
  1 - 4 Years                       0.2
  5 - 9 Years                       0.1
  10 - 14 Years                     0.2
  15 - 19 Years                     0.2
  20 - 24 Years                     0.4
  25 - 29 Years                     0.4
  30 - 34 Years                     0.6
  35 - 39 Years                     1.0
  40 - 44 Years                     1.4
  45 - 49 Years                     2.4
  50 - 54 Years                     4.2
  55 - 59 Years                     7.4
  60 - 64 Years                    10.9
  65 - 69 Years                    18.6
  70 - 74 Years                    31.3
  75 - 79 Years                    47.8
  80 - 84 Years                    78.6
  85 Years & Over                 129.4
Name: 1990, dtype: float64

In [76]:
# Iterate from the second right-most column to the left
for col in reversed(range(len(death_data.columns) - 1)):
    current_col = death_data.columns[col]
    next_col = death_data.columns[col + 1]
    # use mask
    mask = death_data[current_col] == '-'
    death_data.loc[mask, current_col] = death_data.loc[mask, next_col]

print(death_data)

                                 2023   2022   2021   2020   2019   2018  \
Data Series
Male Age Specific Death Rate      6.9    6.9    6.5    5.9    5.6    5.6
  Under 1 Year                    1.9    1.9    1.6    2.1    1.8    2.3
  1 - 4 Years                     0.2    0.2    0.1    0.1    0.1    0.1
  5 - 9 Years                     0.1    0.1    0.1    0.1    0.1    0.1
  10 - 14 Years                   0.2    0.2    0.1    0.1    0.1    0.1
  15 - 19 Years                   0.3    0.2    0.3    0.2    0.2    0.3
  20 - 24 Years                   0.4    0.4    0.3    0.3    0.4    0.4
  25 - 29 Years                   0.5    0.5    0.4    0.3    0.3    0.3
  30 - 34 Years                   0.5    0.5    0.4    0.4    0.4    0.5
  35 - 39 Years                   0.6    0.6    0.7    0.6    0.6    0.6
  40 - 44 Years                   1.0    1.1      1      1      1    0.9
  45 - 49 Years                   1.7    1.8    1.9    1.6    1.7    1.8
  50 - 54 Years                   2.8    3.0    2.9    2.8    2.6    2.8
  55 - 59 Years                   4.9    4.6    5.1    4.7    4.5      5
  60 - 64 Years                   8.1    8.1    8.6    7.9    7.7    8.2
  65 - 69 Years                  13.5   13.2   12.6     12   11.9   12.5
  70 - 74 Years                  20.3   21.6   21.4   20.5   20.2   22.4
  75 - 79 Years                  35.6   36.9     36   35.5   35.3   35.9
  80 - 84 Years                  66.7   69.2   63.7     64   63.5   62.8
  85 Years & Over               137.1  152.8  140.5  123.3  122.2  123.4
Female Age Specific Death Rate    5.5    5.7    5.2    4.5    4.5    4.5
  Under 1 Year                    2.6    1.6    1.9    1.4    1.6    1.9
  1 - 4 Years                     0.1    0.1    0.1    0.1    0.1    0.1
  5 - 9 Years                     0.1    0.1    0.1    0.1    0.1    0.1
  10 - 14 Years                   0.1    0.1    0.1    0.1    0.1    0.1
  15 - 19 Years                   0.2    0.1    0.3    0.1    0.1    0.1
  20 - 24 Years                   0.1    0.2    0.2    0.2    0.1    0.2
  25 - 29 Years                   0.2    0.1    0.2    0.2    0.2    0.2
  30 - 34 Years                   0.2    0.3    0.2    0.2    0.3    0.3
  35 - 39 Years                   0.4    0.5    0.4    0.4    0.3    0.4
  40 - 44 Years                   0.6    0.5    0.6    0.6    0.6    0.5
  45 - 49 Years                   0.9    1.0    1.1      1    0.9      1
  50 - 54 Years                   1.5    1.6    1.8    1.7    1.7    1.8
  55 - 59 Years                   2.6    2.7    2.6    2.7    2.8    2.7
  60 - 64 Years                   3.9    4.5    4.3    3.8    4.2    4.4
  65 - 69 Years                   6.3    7.0    6.8    6.5    6.3    6.6
  70 - 74 Years                  10.9   11.3   10.8   10.1   10.9   11.3
  75 - 79 Years                  19.5   22.1   21.9   18.6   20.7   22.3
  80 - 84 Years                  41.0   43.6   39.7   38.4   38.9   43.2
  85 Years & Over               120.6  122.0  109.1   96.2  100.8  102.7

                                 2017   2016   2015   2014  ...   1999   1998  \
Data Series                                                 ...
Male Age Specific Death Rate      5.5    5.3    5.2    5.2  ...    4.9    5.0
  Under 1 Year                      2    2.3    2.2    1.9  ...    3.2    4.1
  1 - 4 Years                     0.1    0.2    0.2    0.1  ...    0.2    0.3
  5 - 9 Years                     0.1    0.1    0.1    0.1  ...    0.1    0.1
  10 - 14 Years                   0.1    0.2    0.1    0.1  ...    0.2    0.2
  15 - 19 Years                   0.3    0.3    0.2    0.3  ...    0.4    0.4
  20 - 24 Years                   0.3    0.3    0.3    0.4  ...    0.7    0.6
  25 - 29 Years                   0.3    0.4    0.4    0.3  ...    0.6    0.6
  30 - 34 Years                   0.5    0.4    0.5    0.5  ...    0.7    0.8
  35 - 39 Years                   0.7    0.6    0.7    0.7  ...    1.0    1.1
  40 - 44 Years                   1.1    1.1    1.1    1.3  ...    1.7    1.7
  45 - 49 Years                   1.7    1.7    1.9    1.7  ...    2.5    2.8
  50 - 54 Years                   3.1    3.1    3.1      3  ...    4.7    4.9
  55 - 59 Years                   4.8    5.3    5.4    5.8  ...    8.3    9.1
  60 - 64 Years                   8.2    8.2    8.5    8.4  ...   16.0   16.2
  65 - 69 Years                  12.9   13.3   13.9   13.8  ...   25.1   27.4
  70 - 74 Years                  22.9   22.5   23.9   24.4  ...   37.8   41.8
  75 - 79 Years                  37.4   38.4     41     41  ...   64.2   64.9
  80 - 84 Years                  65.5   66.6   63.7   70.6  ...   96.2  103.4
  85 Years & Over               128.9  124.2  124.8  128.5  ...  150.5  135.2
Female Age Specific Death Rate    4.5    4.3    4.3    4.3  ...    4.1    4.1
  Under 1 Year                    2.4    2.5    1.2    1.7  ...    3.4    4.1
  1 - 4 Years                     0.1    0.1    0.1    0.1  ...    0.2    0.3
  5 - 9 Years                     0.1    0.1    0.1    0.1  ...    0.1    0.1
  10 - 14 Years                   0.1    0.1    0.1    0.1  ...    0.2    0.2
  15 - 19 Years                   0.1    0.1    0.2    0.2  ...    0.3    0.3
  20 - 24 Years                   0.1    0.2    0.2    0.1  ...    0.3    0.2
  25 - 29 Years                   0.2    0.2    0.2    0.1  ...    0.3    0.4
  30 - 34 Years                   0.3    0.2    0.3    0.2  ...    0.4    0.4
  35 - 39 Years                   0.3    0.3    0.4    0.3  ...    0.6    0.6
  40 - 44 Years                   0.5    0.8    0.6    0.7  ...    1.0    1.0
  45 - 49 Years                   1.1    1.1    1.1    1.2  ...    1.9    1.7
  50 - 54 Years                     2    1.8    1.9    1.9  ...    2.6    3.2
  55 - 59 Years                     3    3.0    3.1    3.2  ...    4.8    5.1
  60 - 64 Years                   4.5    4.3    4.5    4.4  ...    8.2    9.6
  65 - 69 Years                     7    7.0    7.1    7.5  ...   15.0   15.9
  70 - 74 Years                  11.6   11.5   13.2   13.5  ...   23.2   24.8
  75 - 79 Years                  22.2   23.5   24.4   25.9  ...   44.1   44.4
  80 - 84 Years                  45.4   43.7   43.4   46.6  ...   68.7   71.1
  85 Years & Over               103.4  100.0  108.2  108.8  ...  133.8  128.3

                                 1997   1996   1995   1994   1993   1992  \
Data Series
Male Age Specific Death Rate      4.9    5.2    5.4    5.2    5.0    5.2
  Under 1 Year                    4.0    3.5    4.3    4.3    5.0    5.2
  1 - 4 Years                     0.3    0.4    0.4    0.4    0.3    0.3
  5 - 9 Years                     0.2    0.2    0.2    0.2    0.1    0.3
  10 - 14 Years                   0.2    0.3    0.3    0.3    0.3    0.4
  15 - 19 Years                   0.4    0.5    0.5    0.5    0.5    0.5
  20 - 24 Years                   0.8    0.7    0.7    0.7    0.8    0.8
  25 - 29 Years                   0.6    0.7    0.6    0.7    0.6    0.8
  30 - 34 Years                   0.8    0.8    0.8    0.8    0.7    0.9
  35 - 39 Years                   1.0    1.2    1.3    1.3    1.0    1.2
  40 - 44 Years                   1.9    2.0    1.8    2.0    2.0    2.1
  45 - 49 Years                   2.6    3.1    3.6    3.2    3.4    3.7
  50 - 54 Years                   5.3    5.9    5.8    6.0    6.1    6.1
  55 - 59 Years                   9.2    9.7   10.7   10.5   10.5   10.9
  60 - 64 Years                  16.7   17.9   18.0   17.9   18.4   20.3
  65 - 69 Years                  27.0   28.1   29.6   30.7   29.2   31.0
  70 - 74 Years                  40.9   43.1   46.6   45.4   44.9   46.8
  75 - 79 Years                  67.4   71.1   74.2   70.0   70.0   68.8
  80 - 84 Years                  97.8  104.0  105.2  100.6   89.9   97.6
  85 Years & Over               131.6  141.0  151.4  139.6  137.5  147.1
Female Age Specific Death Rate    4.1    4.2    4.2    4.2    4.2    4.1
  Under 1 Year                    3.1    3.5    3.2    4.0    4.3    4.4
  1 - 4 Years                     0.1    0.2    0.2    0.3    0.3    0.3
  5 - 9 Years                     0.1    0.1    0.2    0.1    0.2    0.1
  10 - 14 Years                   0.1    0.2    0.2    0.2    0.2    0.2
  15 - 19 Years                   0.2    0.3    0.2    0.3    0.2    0.3
  20 - 24 Years                   0.3    0.3    0.3    0.3    0.3    0.3
  25 - 29 Years                   0.3    0.4    0.3    0.3    0.3    0.4
  30 - 34 Years                   0.5    0.5    0.5    0.4    0.5    0.6
  35 - 39 Years                   0.7    0.7    0.8    0.8    0.8    0.7
  40 - 44 Years                   1.1    1.1    1.2    1.1    1.3    1.3
  45 - 49 Years                   1.8    1.8    2.0    2.1    1.9    2.2
  50 - 54 Years                   3.2    3.4    3.5    3.7    3.9    3.9
  55 - 59 Years                   5.3    5.5    6.2    6.6    6.7    6.4
  60 - 64 Years                   9.3    9.4    9.8   10.6   10.2   10.6
  65 - 69 Years                  16.3   16.5   16.7   17.0   17.5   17.8
  70 - 74 Years                  26.3   28.9   30.4   31.7   29.7   28.0
  75 - 79 Years                  45.8   47.8   47.7   47.1   50.6   48.1
  80 - 84 Years                  73.0   71.9   68.0   71.0   69.2   72.9
  85 Years & Over               121.3  128.3  133.8  118.1  129.4  127.0

                                 1991   1990
Data Series
Male Age Specific Death Rate      5.1    5.1
  Under 1 Year                    5.8    7.1
  1 - 4 Years                     0.3    0.4
  5 - 9 Years                     0.2    0.2
  10 - 14 Years                   0.2    0.3
  15 - 19 Years                   0.5    0.5
  20 - 24 Years                   0.7    0.8
  25 - 29 Years                   0.8    0.8
  30 - 34 Years                   0.9    0.9
  35 - 39 Years                   1.2    1.4
  40 - 44 Years                   1.9    2.1
  45 - 49 Years                   3.4    4.0
  50 - 54 Years                   6.7    6.8
  55 - 59 Years                  12.5   12.0
  60 - 64 Years                  20.6   20.8
  65 - 69 Years                  30.2   30.1
  70 - 74 Years                  45.9   46.9
  75 - 79 Years                  67.6   67.3
  80 - 84 Years                 103.1   97.2
  85 Years & Over               135.1  142.3
Female Age Specific Death Rate    4.1    4.3
  Under 1 Year                    4.8    6.2
  1 - 4 Years                     0.3    0.2
  5 - 9 Years                     0.2    0.1
  10 - 14 Years                   0.3    0.2
  15 - 19 Years                   0.3    0.2
  20 - 24 Years                   0.4    0.4
  25 - 29 Years                   0.4    0.4
  30 - 34 Years                   0.5    0.6
  35 - 39 Years                   0.7    1.0
  40 - 44 Years                   1.4    1.4
  45 - 49 Years                   1.9    2.4
  50 - 54 Years                   3.7    4.2
  55 - 59 Years                   6.6    7.4
  60 - 64 Years                  11.0   10.9
  65 - 69 Years                  18.0   18.6
  70 - 74 Years                  31.7   31.3
  75 - 79 Years                  46.1   47.8
  80 - 84 Years                  71.0   78.6
  85 Years & Over               125.2  129.4

[40 rows x 34 columns]

/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_69683/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]
/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_69683/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]
/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_69683/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]
/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_69683/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]
/var/folders/4p/d1jjph_x7hd35z1h1lq9jd3h0000gn/T/ipykernel_69683/785016576.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  death_data.loc[mask, current_col] = death_data.loc[mask, next_col]

In [80]:
# Define the dimensions of the matrix
mortality_matrix = np.zeros((2, 19, 34))

# Simulating popu2 for demonstration (you can replace this with your actual data)

# Initialize and fill the result_matrix
start = 1
for n in range(2):
    end = start + 19
    mortality_matrix[n, :, :] = death_data.iloc[start:end, :].to_numpy()[:, ::-1]  # Reversing columns 0 to 34
    start = end +1

In [85]:
death_data.iloc[1:20,:]

,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
Data Series,,,,,,,,,,,,,,,,,,,,,
Under 1 Year,1.9,1.9,1.6,2.1,1.8,2.3,2,2.3,2.2,1.9,...,3.2,4.1,4.0,3.5,4.3,4.3,5.0,5.2,5.8,7.1
1 - 4 Years,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.1,...,0.2,0.3,0.3,0.4,0.4,0.4,0.3,0.3,0.3,0.4
5 - 9 Years,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,...,0.1,0.1,0.2,0.2,0.2,0.2,0.1,0.3,0.2,0.2
10 - 14 Years,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.2,0.1,0.1,...,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.4,0.2,0.3
15 - 19 Years,0.3,0.2,0.3,0.2,0.2,0.3,0.3,0.3,0.2,0.3,...,0.4,0.4,0.4,0.5,0.5,0.5,0.5,0.5,0.5,0.5
20 - 24 Years,0.4,0.4,0.3,0.3,0.4,0.4,0.3,0.3,0.3,0.4,...,0.7,0.6,0.8,0.7,0.7,0.7,0.8,0.8,0.7,0.8
25 - 29 Years,0.5,0.5,0.4,0.3,0.3,0.3,0.3,0.4,0.4,0.3,...,0.6,0.6,0.6,0.7,0.6,0.7,0.6,0.8,0.8,0.8
30 - 34 Years,0.5,0.5,0.4,0.4,0.4,0.5,0.5,0.4,0.5,0.5,...,0.7,0.8,0.8,0.8,0.8,0.8,0.7,0.9,0.9,0.9
35 - 39 Years,0.6,0.6,0.7,0.6,0.6,0.6,0.7,0.6,0.7,0.7,...,1.0,1.1,1.0,1.2,1.3,1.3,1.0,1.2,1.2,1.4
40 - 44 Years,1.0,1.1,1,1,1,0.9,1.1,1.1,1.1,1.3,...,1.7,1.7,1.9,2.0,1.8,2.0,2.0,2.1,1.9,2.1
45 - 49 Years,1.7,1.8,1.9,1.6,1.7,1.8,1.7,1.7,1.9,1.7,...,2.5,2.8,2.6,3.1,3.6,3.2,3.4,3.7,3.4,4.0
50 - 54 Years,2.8,3.0,2.9,2.8,2.6,2.8,3.1,3.1,3.1,3,...,4.7,4.9,5.3,5.9,5.8,6.0,6.1,6.1,6.7,6.8
55 - 59 Years,4.9,4.6,5.1,4.7,4.5,5,4.8,5.3,5.4,5.8,...,8.3,9.1,9.2,9.7,10.7,10.5,10.5,10.9,12.5,12.0
60 - 64 Years,8.1,8.1,8.6,7.9,7.7,8.2,8.2,8.2,8.5,8.4,...,16.0,16.2,16.7,17.9,18.0,17.9,18.4,20.3,20.6,20.8
65 - 69 Years,13.5,13.2,12.6,12,11.9,12.5,12.9,13.3,13.9,13.8,...,25.1,27.4,27.0,28.1,29.6,30.7,29.2,31.0,30.2,30.1
70 - 74 Years,20.3,21.6,21.4,20.5,20.2,22.4,22.9,22.5,23.9,24.4,...,37.8,41.8,40.9,43.1,46.6,45.4,44.9,46.8,45.9,46.9
75 - 79 Years,35.6,36.9,36,35.5,35.3,35.9,37.4,38.4,41,41,...,64.2,64.9,67.4,71.1,74.2,70.0,70.0,68.8,67.6,67.3
80 - 84 Years,66.7,69.2,63.7,64,63.5,62.8,65.5,66.6,63.7,70.6,...,96.2,103.4,97.8,104.0,105.2,100.6,89.9,97.6,103.1,97.2
85 Years & Over,137.1,152.8,140.5,123.3,122.2,123.4,128.9,124.2,124.8,128.5,...,150.5,135.2,131.6,141.0,151.4,139.6,137.5,147.1,135.1,142.3

In [86]:
mortality_matrix[0,18,:]

array([142.3, 135.1, 147.1, 137.5, 139.6, 151.4, 141. , 131.6, 135.2,
       150.5, 147.7, 143.5, 142.5, 150.1, 146.5, 142.3, 141.9, 145.3,
       135.8, 135.6, 140. , 130.8, 132.3, 131. , 128.5, 124.8, 124.2,
       128.9, 123.4, 122.2, 123.3, 140.5, 152.8, 137.1])

In [ ]:
for i in range(2):
    death_by_year = mortality_matrix[i,:,:]
    initialize a death_by_cohort matrix with 0 
    
    death_by_year, except 1st and last row, expand every row 4 times , get  full_death_table
    
    for ith row, the row should be from (i,0) till (i+33,33) of full_death_table; if the index it outside the matrix
    for the rest of the row, replace it with the last avaliable in the loop.  
    
    
    
# death for people 
# death for people after 1990, or 1990 -2 years old

In [96]:
full_death_table.shape

(86, 34)

In [114]:
full_death_table

array([[7.100e+00, 5.800e+00, 5.200e+00, ..., 1.600e+00, 1.900e+00,
        1.900e+00],
       [4.000e-01, 3.000e-01, 3.000e-01, ..., 1.000e-01, 2.000e-01,
        2.000e-01],
       [4.000e-01, 3.000e-01, 3.000e-01, ..., 1.000e-01, 2.000e-01,
        2.000e-01],
       ...,
       [9.720e+01, 1.031e+02, 9.760e+01, ..., 6.370e+01, 6.920e+01,
        6.670e+01],
       [9.720e+01, 1.031e+02, 9.760e+01, ..., 6.370e+01, 6.920e+01,
        6.670e+01],
       [1.423e+02, 1.351e+02, 1.471e+02, ..., 1.405e+02, 1.528e+02,
        1.371e+02]])

In [119]:
import numpy as np

# Assuming mortality_matrix is already defined
death_by_cohort = np.zeros((2,86, 34))  # male, female; 0 - 85, 85+; for 1990 - 2023

for i in range(2):
    death_by_year = mortality_matrix[i, :, :]
    # Expand every row 5 times to get mortality rate from 0 - 85+
    death_table_4 = np.repeat(death_by_year[1:2], 4, axis=0)
    full_death_table = np.repeat(death_by_year[2:-1], 5, axis=0)
    full_death_table = np.vstack((death_by_year[0],death_table_4, full_death_table, death_by_year[-1]))

    # Iterate through each row and generate the death_by_cohort
    for j in range(86):
    
        # modify and check boundary
        # initialize vec with 0 
        vec = np.zeros(34)
        # for the upper matrix 
        
        for k in range(34):
                row_idx = min(85, j+k)
                vec[k] = full_death_table[row_idx, k]
            # diagnosis first, and then horizontal
             
        death_by_cohort[i, j, :] = vec
        # Fill the rest of the row with the last available value

In [125]:
full_death_table.shape # 86 * 34; 0-85, 85+; 1990 - 2023

(86, 34)

In [122]:
print(mortality_matrix[0, :, :])

[[7.100e+00 5.800e+00 5.200e+00 5.000e+00 4.300e+00 4.300e+00 3.500e+00
  4.000e+00 4.100e+00 3.200e+00 2.800e+00 2.400e+00 3.400e+00 2.800e+00
  2.200e+00 2.400e+00 2.800e+00 2.600e+00 2.600e+00 2.600e+00 1.900e+00
  2.300e+00 2.000e+00 1.800e+00 1.900e+00 2.200e+00 2.300e+00 2.000e+00
  2.300e+00 1.800e+00 2.100e+00 1.600e+00 1.900e+00 1.900e+00]
 [4.000e-01 3.000e-01 3.000e-01 3.000e-01 4.000e-01 4.000e-01 4.000e-01
  3.000e-01 3.000e-01 2.000e-01 3.000e-01 3.000e-01 2.000e-01 2.000e-01
  2.000e-01 2.000e-01 1.000e-01 1.000e-01 1.000e-01 2.000e-01 2.000e-01
  2.000e-01 2.000e-01 1.000e-01 1.000e-01 2.000e-01 2.000e-01 1.000e-01
  1.000e-01 1.000e-01 1.000e-01 1.000e-01 2.000e-01 2.000e-01]
 [2.000e-01 2.000e-01 3.000e-01 1.000e-01 2.000e-01 2.000e-01 2.000e-01
  2.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 2.000e-01
  1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01
  1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01
  1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01]
 [3.000e-01 2.000e-01 4.000e-01 3.000e-01 3.000e-01 3.000e-01 3.000e-01
  2.000e-01 2.000e-01 2.000e-01 3.000e-01 1.000e-01 1.000e-01 2.000e-01
  1.000e-01 1.000e-01 2.000e-01 1.000e-01 1.000e-01 2.000e-01 1.000e-01
  1.000e-01 2.000e-01 1.000e-01 1.000e-01 1.000e-01 2.000e-01 1.000e-01
  1.000e-01 1.000e-01 1.000e-01 1.000e-01 2.000e-01 2.000e-01]
 [5.000e-01 5.000e-01 5.000e-01 5.000e-01 5.000e-01 5.000e-01 5.000e-01
  4.000e-01 4.000e-01 4.000e-01 3.000e-01 4.000e-01 3.000e-01 5.000e-01
  3.000e-01 3.000e-01 2.000e-01 2.000e-01 3.000e-01 3.000e-01 2.000e-01
  2.000e-01 2.000e-01 3.000e-01 3.000e-01 2.000e-01 3.000e-01 3.000e-01
  3.000e-01 2.000e-01 2.000e-01 3.000e-01 2.000e-01 3.000e-01]
 [8.000e-01 7.000e-01 8.000e-01 8.000e-01 7.000e-01 7.000e-01 7.000e-01
  8.000e-01 6.000e-01 7.000e-01 7.000e-01 7.000e-01 6.000e-01 8.000e-01
  7.000e-01 6.000e-01 5.000e-01 6.000e-01 4.000e-01 5.000e-01 4.000e-01
  5.000e-01 5.000e-01 4.000e-01 4.000e-01 3.000e-01 3.000e-01 3.000e-01
  4.000e-01 4.000e-01 3.000e-01 3.000e-01 4.000e-01 4.000e-01]
 [8.000e-01 8.000e-01 8.000e-01 6.000e-01 7.000e-01 6.000e-01 7.000e-01
  6.000e-01 6.000e-01 6.000e-01 6.000e-01 7.000e-01 6.000e-01 6.000e-01
  4.000e-01 5.000e-01 5.000e-01 7.000e-01 5.000e-01 5.000e-01 4.000e-01
  4.000e-01 4.000e-01 3.000e-01 3.000e-01 4.000e-01 4.000e-01 3.000e-01
  3.000e-01 3.000e-01 3.000e-01 4.000e-01 5.000e-01 5.000e-01]
 [9.000e-01 9.000e-01 9.000e-01 7.000e-01 8.000e-01 8.000e-01 8.000e-01
  8.000e-01 8.000e-01 7.000e-01 8.000e-01 7.000e-01 6.000e-01 8.000e-01
  7.000e-01 6.000e-01 6.000e-01 5.000e-01 5.000e-01 6.000e-01 4.000e-01
  5.000e-01 4.000e-01 6.000e-01 5.000e-01 5.000e-01 4.000e-01 5.000e-01
  5.000e-01 4.000e-01 4.000e-01 4.000e-01 5.000e-01 5.000e-01]
 [1.400e+00 1.200e+00 1.200e+00 1.000e+00 1.300e+00 1.300e+00 1.200e+00
  1.000e+00 1.100e+00 1.000e+00 1.300e+00 1.000e+00 1.100e+00 9.000e-01
  9.000e-01 1.000e+00 9.000e-01 9.000e-01 9.000e-01 8.000e-01 8.000e-01
  7.000e-01 6.000e-01 6.000e-01 7.000e-01 7.000e-01 6.000e-01 7.000e-01
  6.000e-01 6.000e-01 6.000e-01 7.000e-01 6.000e-01 6.000e-01]
 [2.100e+00 1.900e+00 2.100e+00 2.000e+00 2.000e+00 1.800e+00 2.000e+00
  1.900e+00 1.700e+00 1.700e+00 1.800e+00 1.600e+00 1.600e+00 1.600e+00
  1.600e+00 1.500e+00 1.600e+00 1.500e+00 1.400e+00 1.200e+00 1.300e+00
  1.000e+00 1.200e+00 1.200e+00 1.300e+00 1.100e+00 1.100e+00 1.100e+00
  9.000e-01 1.000e+00 1.000e+00 1.000e+00 1.100e+00 1.000e+00]
 [4.000e+00 3.400e+00 3.700e+00 3.400e+00 3.200e+00 3.600e+00 3.100e+00
  2.600e+00 2.800e+00 2.500e+00 2.700e+00 2.500e+00 2.700e+00 2.700e+00
  2.400e+00 2.400e+00 2.300e+00 2.300e+00 2.400e+00 2.000e+00 2.200e+00
  2.200e+00 1.900e+00 2.000e+00 1.700e+00 1.900e+00 1.700e+00 1.700e+00
  1.800e+00 1.700e+00 1.600e+00 1.900e+00 1.800e+00 1.700e+00]
 [6.800e+00 6.700e+00 6.100e+00 6.100e+00 6.000e+00 5.800e+00 5.900e+00
  5.300e+00 4.900e+00 4.700e+00 4.200e+00 4.700e+00 4.300e+00 4.200e+00
  4.200e+00 4.400e+00 4.000e+00 4.100e+00 4.000e+00 3.900e+00 3.900e+00
  3.600e+00 3.100e+00 3.400e+00 3.000e+00 3.100e+00 3.100e+00 3.100e+00
  2.800e+00 2.600e+00 2.800e+00 2.900e+00 3.000e+00 2.800e+00]
 [1.200e+01 1.250e+01 1.090e+01 1.050e+01 1.050e+01 1.070e+01 9.700e+00
  9.200e+00 9.100e+00 8.300e+00 7.900e+00 8.200e+00 8.400e+00 7.600e+00
  7.200e+00 7.500e+00 6.600e+00 6.500e+00 6.600e+00 6.000e+00 5.700e+00
  5.900e+00 5.800e+00 5.700e+00 5.800e+00 5.400e+00 5.300e+00 4.800e+00
  5.000e+00 4.500e+00 4.700e+00 5.100e+00 4.600e+00 4.900e+00]
 [2.080e+01 2.060e+01 2.030e+01 1.840e+01 1.790e+01 1.800e+01 1.790e+01
  1.670e+01 1.620e+01 1.600e+01 1.440e+01 1.330e+01 1.310e+01 1.330e+01
  1.230e+01 1.170e+01 1.160e+01 1.120e+01 1.060e+01 9.900e+00 9.400e+00
  8.900e+00 9.700e+00 8.800e+00 8.400e+00 8.500e+00 8.200e+00 8.200e+00
  8.200e+00 7.700e+00 7.900e+00 8.600e+00 8.100e+00 8.100e+00]
 [3.010e+01 3.020e+01 3.100e+01 2.920e+01 3.070e+01 2.960e+01 2.810e+01
  2.700e+01 2.740e+01 2.510e+01 2.450e+01 2.350e+01 2.260e+01 2.300e+01
  2.120e+01 2.170e+01 1.830e+01 1.910e+01 1.830e+01 1.630e+01 1.660e+01
  1.640e+01 1.520e+01 1.450e+01 1.380e+01 1.390e+01 1.330e+01 1.290e+01
  1.250e+01 1.190e+01 1.200e+01 1.260e+01 1.320e+01 1.350e+01]
 [4.690e+01 4.590e+01 4.680e+01 4.490e+01 4.540e+01 4.660e+01 4.310e+01
  4.090e+01 4.180e+01 3.780e+01 3.640e+01 3.630e+01 3.400e+01 3.730e+01
  3.480e+01 3.200e+01 3.070e+01 3.220e+01 3.030e+01 2.860e+01 2.710e+01
  2.600e+01 2.650e+01 2.600e+01 2.440e+01 2.390e+01 2.250e+01 2.290e+01
  2.240e+01 2.020e+01 2.050e+01 2.140e+01 2.160e+01 2.030e+01]
 [6.730e+01 6.760e+01 6.880e+01 7.000e+01 7.000e+01 7.420e+01 7.110e+01
  6.740e+01 6.490e+01 6.420e+01 6.160e+01 5.460e+01 5.370e+01 6.550e+01
  5.730e+01 5.130e+01 5.320e+01 5.210e+01 4.880e+01 4.690e+01 4.520e+01
  4.720e+01 4.230e+01 4.330e+01 4.100e+01 4.100e+01 3.840e+01 3.740e+01
  3.590e+01 3.530e+01 3.550e+01 3.600e+01 3.690e+01 3.560e+01]
 [9.720e+01 1.031e+02 9.760e+01 8.990e+01 1.006e+02 1.052e+02 1.040e+02
  9.780e+01 1.034e+02 9.620e+01 1.030e+02 9.020e+01 9.030e+01 8.960e+01
  8.790e+01 8.750e+01 8.450e+01 8.670e+01 7.950e+01 7.340e+01 7.640e+01
  7.130e+01 6.990e+01 6.820e+01 7.060e+01 6.370e+01 6.660e+01 6.550e+01
  6.280e+01 6.350e+01 6.400e+01 6.370e+01 6.920e+01 6.670e+01]
 [1.423e+02 1.351e+02 1.471e+02 1.375e+02 1.396e+02 1.514e+02 1.410e+02
  1.316e+02 1.352e+02 1.505e+02 1.477e+02 1.435e+02 1.425e+02 1.501e+02
  1.465e+02 1.423e+02 1.419e+02 1.453e+02 1.358e+02 1.356e+02 1.400e+02
  1.308e+02 1.323e+02 1.310e+02 1.285e+02 1.248e+02 1.242e+02 1.289e+02
  1.234e+02 1.222e+02 1.233e+02 1.405e+02 1.528e+02 1.371e+02]]

In [127]:
death_by_cohort[0,:,:]

array([[  7.1,   0.3,   0.3, ...,   0.4,   0.5,   0.5],
       [  0.4,   0.3,   0.3, ...,   0.4,   0.5,   0.5],
       [  0.4,   0.3,   0.3, ...,   0.4,   0.5,   0.6],
       ...,
       [ 97.2, 103.1, 147.1, ..., 140.5, 152.8, 137.1],
       [ 97.2, 135.1, 147.1, ..., 140.5, 152.8, 137.1],
       [142.3, 135.1, 147.1, ..., 140.5, 152.8, 137.1]])

In [129]:
import numpy as np

# Generate a random population matrix of size 86 * 34
population_matrix = np.random.rand(86, 34)

# Assume death_by_cohort is already defined, and get the matrix to compare
matrix = death_by_cohort[0, :, :] / 1000

# Perform element-wise comparison and return 0/1 matrix
comparison_matrix = (population_matrix <= matrix).astype(int)

# Display the result
comparison_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0]])

In [132]:
import pandas as pd

# Create a list of years for the columns
years = list(range(1990, 2025))  # 1990 to 2024

# Create a list of age group labels for the rows
age_groups = [str(i) for i in range(85)] + ['85+']  # Age groups 0-85 and '85+'

# Convert the numpy array to a DataFrame, set column names to years and row names to age groups
comparison_df = pd.DataFrame(comparison_matrix, columns=years, index=age_groups)

# Save the DataFrame to a CSV file
comparison_df.to_csv('comparison_matrix.csv', index=True)

# Display a success message
print("The comparison matrix has been saved to 'comparison_matrix.csv' with the appropriate row and column names.")

ValueError: Shape of passed values is (86, 34), indices imply (87, 35)

In [130]:
import pandas as pd

# Convert the numpy array to a DataFrame
comparison_df = pd.DataFrame(comparison_matrix)

# Save the DataFrame to a CSV file
comparison_df.to_csv('comparison_matrix.csv', index=False)

# Display a success message
print("The comparison matrix has been saved to 'comparison_matrix.csv'")

The comparison matrix has been saved to 'comparison_matrix.csv'

In [124]:
death_data.iloc[1:20, ::-1]

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Data Series,,,,,,,,,,,,,,,,,,,,,
Under 1 Year,7.1,5.8,5.2,5.0,4.3,4.3,3.5,4.0,4.1,3.2,...,1.9,2.2,2.3,2,2.3,1.8,2.1,1.6,1.9,1.9
1 - 4 Years,0.4,0.3,0.3,0.3,0.4,0.4,0.4,0.3,0.3,0.2,...,0.1,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.2,0.2
5 - 9 Years,0.2,0.2,0.3,0.1,0.2,0.2,0.2,0.2,0.1,0.1,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
10 - 14 Years,0.3,0.2,0.4,0.3,0.3,0.3,0.3,0.2,0.2,0.2,...,0.1,0.1,0.2,0.1,0.1,0.1,0.1,0.1,0.2,0.2
15 - 19 Years,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.4,0.4,0.4,...,0.3,0.2,0.3,0.3,0.3,0.2,0.2,0.3,0.2,0.3
20 - 24 Years,0.8,0.7,0.8,0.8,0.7,0.7,0.7,0.8,0.6,0.7,...,0.4,0.3,0.3,0.3,0.4,0.4,0.3,0.3,0.4,0.4
25 - 29 Years,0.8,0.8,0.8,0.6,0.7,0.6,0.7,0.6,0.6,0.6,...,0.3,0.4,0.4,0.3,0.3,0.3,0.3,0.4,0.5,0.5
30 - 34 Years,0.9,0.9,0.9,0.7,0.8,0.8,0.8,0.8,0.8,0.7,...,0.5,0.5,0.4,0.5,0.5,0.4,0.4,0.4,0.5,0.5
35 - 39 Years,1.4,1.2,1.2,1.0,1.3,1.3,1.2,1.0,1.1,1.0,...,0.7,0.7,0.6,0.7,0.6,0.6,0.6,0.7,0.6,0.6
40 - 44 Years,2.1,1.9,2.1,2.0,2.0,1.8,2.0,1.9,1.7,1.7,...,1.3,1.1,1.1,1.1,0.9,1,1,1,1.1,1.0
45 - 49 Years,4.0,3.4,3.7,3.4,3.2,3.6,3.1,2.6,2.8,2.5,...,1.7,1.9,1.7,1.7,1.8,1.7,1.6,1.9,1.8,1.7
50 - 54 Years,6.8,6.7,6.1,6.1,6.0,5.8,5.9,5.3,4.9,4.7,...,3,3.1,3.1,3.1,2.8,2.6,2.8,2.9,3.0,2.8
55 - 59 Years,12.0,12.5,10.9,10.5,10.5,10.7,9.7,9.2,9.1,8.3,...,5.8,5.4,5.3,4.8,5,4.5,4.7,5.1,4.6,4.9
60 - 64 Years,20.8,20.6,20.3,18.4,17.9,18.0,17.9,16.7,16.2,16.0,...,8.4,8.5,8.2,8.2,8.2,7.7,7.9,8.6,8.1,8.1
65 - 69 Years,30.1,30.2,31.0,29.2,30.7,29.6,28.1,27.0,27.4,25.1,...,13.8,13.9,13.3,12.9,12.5,11.9,12,12.6,13.2,13.5
70 - 74 Years,46.9,45.9,46.8,44.9,45.4,46.6,43.1,40.9,41.8,37.8,...,24.4,23.9,22.5,22.9,22.4,20.2,20.5,21.4,21.6,20.3
75 - 79 Years,67.3,67.6,68.8,70.0,70.0,74.2,71.1,67.4,64.9,64.2,...,41,41,38.4,37.4,35.9,35.3,35.5,36,36.9,35.6
80 - 84 Years,97.2,103.1,97.6,89.9,100.6,105.2,104.0,97.8,103.4,96.2,...,70.6,63.7,66.6,65.5,62.8,63.5,64,63.7,69.2,66.7
85 Years & Over,142.3,135.1,147.1,137.5,139.6,151.4,141.0,131.6,135.2,150.5,...,128.5,124.8,124.2,128.9,123.4,122.2,123.3,140.5,152.8,137.1

In [123]:
death_data.iloc[21:40, ::-1]

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Data Series,,,,,,,,,,,,,,,,,,,,,
Under 1 Year,6.2,4.8,4.4,4.3,4.0,3.2,3.5,3.1,4.1,3.4,...,1.7,1.2,2.5,2.4,1.9,1.6,1.4,1.9,1.6,2.6
1 - 4 Years,0.2,0.3,0.3,0.3,0.3,0.2,0.2,0.1,0.3,0.2,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
5 - 9 Years,0.1,0.2,0.1,0.2,0.1,0.2,0.1,0.1,0.1,0.1,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
10 - 14 Years,0.2,0.3,0.2,0.2,0.2,0.2,0.2,0.1,0.2,0.2,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
15 - 19 Years,0.2,0.3,0.3,0.2,0.3,0.2,0.3,0.2,0.3,0.3,...,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.3,0.1,0.2
20 - 24 Years,0.4,0.4,0.3,0.3,0.3,0.3,0.3,0.3,0.2,0.3,...,0.1,0.2,0.2,0.1,0.2,0.1,0.2,0.2,0.2,0.1
25 - 29 Years,0.4,0.4,0.4,0.3,0.3,0.3,0.4,0.3,0.4,0.3,...,0.1,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.1,0.2
30 - 34 Years,0.6,0.5,0.6,0.5,0.4,0.5,0.5,0.5,0.4,0.4,...,0.2,0.3,0.2,0.3,0.3,0.3,0.2,0.2,0.3,0.2
35 - 39 Years,1.0,0.7,0.7,0.8,0.8,0.8,0.7,0.7,0.6,0.6,...,0.3,0.4,0.3,0.3,0.4,0.3,0.4,0.4,0.5,0.4
40 - 44 Years,1.4,1.4,1.3,1.3,1.1,1.2,1.1,1.1,1.0,1.0,...,0.7,0.6,0.8,0.5,0.5,0.6,0.6,0.6,0.5,0.6
45 - 49 Years,2.4,1.9,2.2,1.9,2.1,2.0,1.8,1.8,1.7,1.9,...,1.2,1.1,1.1,1.1,1,0.9,1,1.1,1.0,0.9
50 - 54 Years,4.2,3.7,3.9,3.9,3.7,3.5,3.4,3.2,3.2,2.6,...,1.9,1.9,1.8,2,1.8,1.7,1.7,1.8,1.6,1.5
55 - 59 Years,7.4,6.6,6.4,6.7,6.6,6.2,5.5,5.3,5.1,4.8,...,3.2,3.1,3.0,3,2.7,2.8,2.7,2.6,2.7,2.6
60 - 64 Years,10.9,11.0,10.6,10.2,10.6,9.8,9.4,9.3,9.6,8.2,...,4.4,4.5,4.3,4.5,4.4,4.2,3.8,4.3,4.5,3.9
65 - 69 Years,18.6,18.0,17.8,17.5,17.0,16.7,16.5,16.3,15.9,15.0,...,7.5,7.1,7.0,7,6.6,6.3,6.5,6.8,7.0,6.3
70 - 74 Years,31.3,31.7,28.0,29.7,31.7,30.4,28.9,26.3,24.8,23.2,...,13.5,13.2,11.5,11.6,11.3,10.9,10.1,10.8,11.3,10.9
75 - 79 Years,47.8,46.1,48.1,50.6,47.1,47.7,47.8,45.8,44.4,44.1,...,25.9,24.4,23.5,22.2,22.3,20.7,18.6,21.9,22.1,19.5
80 - 84 Years,78.6,71.0,72.9,69.2,71.0,68.0,71.9,73.0,71.1,68.7,...,46.6,43.4,43.7,45.4,43.2,38.9,38.4,39.7,43.6,41.0
85 Years & Over,129.4,125.2,127.0,129.4,118.1,133.8,128.3,121.3,128.3,133.8,...,108.8,108.2,100.0,103.4,102.7,100.8,96.2,109.1,122.0,120.6

In [67]:
death_data.iloc[1:20,:]

,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
Data Series,,,,,,,,,,,,,,,,,,,,,
Under 1 Year,1.9,1.9,1.6,2.1,1.8,2.3,2,2.3,2.2,1.9,...,3.2,4.1,4.0,3.5,4.3,4.3,5.0,5.2,5.8,7.1
1 - 4 Years,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.1,...,0.2,0.3,0.3,0.4,0.4,0.4,0.3,0.3,0.3,0.4
5 - 9 Years,0.1,0.1,-,-,0.1,-,0.1,0.1,0.1,-,...,0.1,0.1,0.2,0.2,0.2,0.2,0.1,0.3,0.2,0.2
10 - 14 Years,0.2,0.2,0.1,0.1,-,0.1,0.1,0.2,0.1,-,...,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.4,0.2,0.3
15 - 19 Years,0.3,0.2,0.3,0.2,0.2,0.3,0.3,0.3,0.2,0.3,...,0.4,0.4,0.4,0.5,0.5,0.5,0.5,0.5,0.5,0.5
20 - 24 Years,0.4,0.4,0.3,0.3,0.4,0.4,0.3,0.3,0.3,0.4,...,0.7,0.6,0.8,0.7,0.7,0.7,0.8,0.8,0.7,0.8
25 - 29 Years,0.5,0.5,0.4,0.3,0.3,0.3,0.3,0.4,0.4,0.3,...,0.6,0.6,0.6,0.7,0.6,0.7,0.6,0.8,0.8,0.8
30 - 34 Years,0.5,0.5,0.4,0.4,0.4,0.5,0.5,0.4,0.5,0.5,...,0.7,0.8,0.8,0.8,0.8,0.8,0.7,0.9,0.9,0.9
35 - 39 Years,0.6,0.6,0.7,0.6,0.6,0.6,0.7,0.6,0.7,0.7,...,1.0,1.1,1.0,1.2,1.3,1.3,1.0,1.2,1.2,1.4
40 - 44 Years,1.0,1.1,1,1,1,0.9,1.1,1.1,1.1,1.3,...,1.7,1.7,1.9,2.0,1.8,2.0,2.0,2.1,1.9,2.1
45 - 49 Years,1.7,1.8,1.9,1.6,1.7,1.8,1.7,1.7,1.9,1.7,...,2.5,2.8,2.6,3.1,3.6,3.2,3.4,3.7,3.4,4.0
50 - 54 Years,2.8,3.0,2.9,2.8,2.6,2.8,3.1,3.1,3.1,3,...,4.7,4.9,5.3,5.9,5.8,6.0,6.1,6.1,6.7,6.8
55 - 59 Years,4.9,4.6,5.1,4.7,4.5,5,4.8,5.3,5.4,5.8,...,8.3,9.1,9.2,9.7,10.7,10.5,10.5,10.9,12.5,12.0
60 - 64 Years,8.1,8.1,8.6,7.9,7.7,8.2,8.2,8.2,8.5,8.4,...,16.0,16.2,16.7,17.9,18.0,17.9,18.4,20.3,20.6,20.8
65 - 69 Years,13.5,13.2,12.6,12,11.9,12.5,12.9,13.3,13.9,13.8,...,25.1,27.4,27.0,28.1,29.6,30.7,29.2,31.0,30.2,30.1
70 - 74 Years,20.3,21.6,21.4,20.5,20.2,22.4,22.9,22.5,23.9,24.4,...,37.8,41.8,40.9,43.1,46.6,45.4,44.9,46.8,45.9,46.9
75 - 79 Years,35.6,36.9,36,35.5,35.3,35.9,37.4,38.4,41,41,...,64.2,64.9,67.4,71.1,74.2,70.0,70.0,68.8,67.6,67.3
80 - 84 Years,66.7,69.2,63.7,64,63.5,62.8,65.5,66.6,63.7,70.6,...,96.2,103.4,97.8,104.0,105.2,100.6,89.9,97.6,103.1,97.2

In [63]:
death_data

,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
Data Series,,,,,,,,,,,,,,,,,,,,,
Male Age Specific Death Rate,6.9,6.9,6.5,5.9,5.6,5.6,5.5,5.3,5.2,5.2,...,4.9,5.0,4.9,5.2,5.4,5.2,5.0,5.2,5.1,5.1
Under 1 Year,1.9,1.9,1.6,2.1,1.8,2.3,2,2.3,2.2,1.9,...,3.2,4.1,4.0,3.5,4.3,4.3,5.0,5.2,5.8,7.1
1 - 4 Years,0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.2,0.2,0.1,...,0.2,0.3,0.3,0.4,0.4,0.4,0.3,0.3,0.3,0.4
5 - 9 Years,0.1,0.1,-,-,0.1,-,0.1,0.1,0.1,-,...,0.1,0.1,0.2,0.2,0.2,0.2,0.1,0.3,0.2,0.2
10 - 14 Years,0.2,0.2,0.1,0.1,-,0.1,0.1,0.2,0.1,-,...,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.4,0.2,0.3
15 - 19 Years,0.3,0.2,0.3,0.2,0.2,0.3,0.3,0.3,0.2,0.3,...,0.4,0.4,0.4,0.5,0.5,0.5,0.5,0.5,0.5,0.5
20 - 24 Years,0.4,0.4,0.3,0.3,0.4,0.4,0.3,0.3,0.3,0.4,...,0.7,0.6,0.8,0.7,0.7,0.7,0.8,0.8,0.7,0.8
25 - 29 Years,0.5,0.5,0.4,0.3,0.3,0.3,0.3,0.4,0.4,0.3,...,0.6,0.6,0.6,0.7,0.6,0.7,0.6,0.8,0.8,0.8
30 - 34 Years,0.5,0.5,0.4,0.4,0.4,0.5,0.5,0.4,0.5,0.5,...,0.7,0.8,0.8,0.8,0.8,0.8,0.7,0.9,0.9,0.9
35 - 39 Years,0.6,0.6,0.7,0.6,0.6,0.6,0.7,0.6,0.7,0.7,...,1.0,1.1,1.0,1.2,1.3,1.3,1.0,1.2,1.2,1.4
40 - 44 Years,1.0,1.1,1,1,1,0.9,1.1,1.1,1.1,1.3,...,1.7,1.7,1.9,2.0,1.8,2.0,2.0,2.1,1.9,2.1
45 - 49 Years,1.7,1.8,1.9,1.6,1.7,1.8,1.7,1.7,1.9,1.7,...,2.5,2.8,2.6,3.1,3.6,3.2,3.4,3.7,3.4,4.0
50 - 54 Years,2.8,3.0,2.9,2.8,2.6,2.8,3.1,3.1,3.1,3,...,4.7,4.9,5.3,5.9,5.8,6.0,6.1,6.1,6.7,6.8
55 - 59 Years,4.9,4.6,5.1,4.7,4.5,5,4.8,5.3,5.4,5.8,...,8.3,9.1,9.2,9.7,10.7,10.5,10.5,10.9,12.5,12.0
60 - 64 Years,8.1,8.1,8.6,7.9,7.7,8.2,8.2,8.2,8.5,8.4,...,16.0,16.2,16.7,17.9,18.0,17.9,18.4,20.3,20.6,20.8
65 - 69 Years,13.5,13.2,12.6,12,11.9,12.5,12.9,13.3,13.9,13.8,...,25.1,27.4,27.0,28.1,29.6,30.7,29.2,31.0,30.2,30.1
70 - 74 Years,20.3,21.6,21.4,20.5,20.2,22.4,22.9,22.5,23.9,24.4,...,37.8,41.8,40.9,43.1,46.6,45.4,44.9,46.8,45.9,46.9
75 - 79 Years,35.6,36.9,36,35.5,35.3,35.9,37.4,38.4,41,41,...,64.2,64.9,67.4,71.1,74.2,70.0,70.0,68.8,67.6,67.3
80 - 84 Years,66.7,69.2,63.7,64,63.5,62.8,65.5,66.6,63.7,70.6,...,96.2,103.4,97.8,104.0,105.2,100.6,89.9,97.6,103.1,97.2
85 Years & Over,137.1,152.8,140.5,123.3,122.2,123.4,128.9,124.2,124.8,128.5,...,150.5,135.2,131.6,141.0,151.4,139.6,137.5,147.1,135.1,142.3
Female Age Specific Death Rate,5.5,5.7,5.2,4.5,4.5,4.5,4.5,4.3,4.3,4.3,...,4.1,4.1,4.1,4.2,4.2,4.2,4.2,4.1,4.1,4.3
Under 1 Year,2.6,1.6,1.9,1.4,1.6,1.9,2.4,2.5,1.2,1.7,...,3.4,4.1,3.1,3.5,3.2,4.0,4.3,4.4,4.8,6.2
1 - 4 Years,0.1,0.1,0.1,-,0.1,0.1,0.1,0.1,0.1,0.1,...,0.2,0.3,0.1,0.2,0.2,0.3,0.3,0.3,0.3,0.2
5 - 9 Years,0.1,0.1,0.1,0.1,0.1,0.1,-,0.1,-,-,...,0.1,0.1,0.1,0.1,0.2,0.1,0.2,0.1,0.2,0.1
10 - 14 Years,0.1,0.1,0.1,0.1,-,0.1,0.1,0.1,0.1,0.1,...,0.2,0.2,0.1,0.2,0.2,0.2,0.2,0.2,0.3,0.2
15 - 19 Years,0.2,0.1,0.3,0.1,0.1,0.1,0.1,0.1,0.2,0.2,...,0.3,0.3,0.2,0.3,0.2,0.3,0.2,0.3,0.3,0.2
20 - 24 Years,0.1,0.2,0.2,0.2,0.1,0.2,0.1,0.2,0.2,0.1,...,0.3,0.2,0.3,0.3,0.3,0.3,0.3,0.3,0.4,0.4
25 - 29 Years,0.2,0.1,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.1,...,0.3,0.4,0.3,0.4,0.3,0.3,0.3,0.4,0.4,0.4
30 - 34 Years,0.2,0.3,0.2,0.2,0.3,0.3,0.3,0.2,0.3,0.2,...,0.4,0.4,0.5,0.5,0.5,0.4,0.5,0.6,0.5,0.6
35 - 39 Years,0.4,0.5,0.4,0.4,0.3,0.4,0.3,0.3,0.4,0.3,...,0.6,0.6,0.7,0.7,0.8,0.8,0.8,0.7,0.7,1.0
40 - 44 Years,0.6,0.5,0.6,0.6,0.6,0.5,0.5,0.8,0.6,0.7,...,1.0,1.0,1.1,1.1,1.2,1.1,1.3,1.3,1.4,1.4
45 - 49 Years,0.9,1.0,1.1,1,0.9,1,1.1,1.1,1.1,1.2,...,1.9,1.7,1.8,1.8,2.0,2.1,1.9,2.2,1.9,2.4
50 - 54 Years,1.5,1.6,1.8,1.7,1.7,1.8,2,1.8,1.9,1.9,...,2.6,3.2,3.2,3.4,3.5,3.7,3.9,3.9,3.7,4.2
55 - 59 Years,2.6,2.7,2.6,2.7,2.8,2.7,3,3.0,3.1,3.2,...,4.8,5.1,5.3,5.5,6.2,6.6,6.7,6.4,6.6,7.4
60 - 64 Years,3.9,4.5,4.3,3.8,4.2,4.4,4.5,4.3,4.5,4.4,...,8.2,9.6,9.3,9.4,9.8,10.6,10.2,10.6,11.0,10.9
65 - 69 Years,6.3,7.0,6.8,6.5,6.3,6.6,7,7.0,7.1,7.5,...,15.0,15.9,16.3,16.5,16.7,17.0,17.5,17.8,18.0,18.6
70 - 74 Years,10.9,11.3,10.8,10.1,10.9,11.3,11.6,11.5,13.2,13.5,...,23.2,24.8,26.3,28.9,30.4,31.7,29.7,28.0,31.7,31.3
75 - 79 Years,19.5,22.1,21.9,18.6,20.7,22.3,22.2,23.5,24.4,25.9,...,44.1,44.4,45.8,47.8,47.7,47.1,50.6,48.1,46.1,47.8
80 - 84 Years,41.0,43.6,39.7,38.4,38.9,43.2,45.4,43.7,43.4,46.6,...,68.7,71.1,73.0,71.9,68.0,71.0,69.2,72.9,71.0,78.6
85 Years & Over,120.6,122.0,109.1,96.2,100.8,102.7,103.4,100.0,108.2,108.8,...,133.8,128.3,121.3,128.3,133.8,118.1,129.4,127.0,125.2,129.4